version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
    - image: circleci/node:8-browsers
    steps:
    - checkout
    - restore_cache:
        key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
    - run: npm install
    - save_cache:
        key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - "node_modules"
    - run: yarn test --watch=false
    - run: yarn lint