version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - restore_cache: # special step to restore the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Setup Dependencies
        command: npm install
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run: # run tests
        name: Run Test
        command: npm run test
    - run: # run lint and fix
        name: Run lint
        command: npm run lint
